name: SkyBlockAddon
version: '${project.version}'
main: fun.mcbee.plugin.skyblockaddon.SkyBlockAddon
api-version: 1.18
authors: [ PxLib ]
commands:
  spawn:
    aliases: [lobby]
  hat:
    aliases: [hat]
    permission: bee.honey.hat
